name: Feature Request
description: Suggest an idea for this project
type: Feature
body:
- type: textarea
  attributes:
    label: Feature Description
    placeholder: "Describe a feature you'd like us to add. If it's not obvious, explain why this feature is awesome. Note that feature requests must be specific and measurable."
